/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BeaconListenerImpl */

#ifndef _Included_BeaconListenerImpl
#define _Included_BeaconListenerImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef BeaconListenerImpl_serialVersionUID
#define BeaconListenerImpl_serialVersionUID -3215090123894869218LL
#undef BeaconListenerImpl_serialVersionUID
#define BeaconListenerImpl_serialVersionUID -4100238210092549637LL
#undef BeaconListenerImpl_serialVersionUID
#define BeaconListenerImpl_serialVersionUID 4974527148936298033LL
#undef BeaconListenerImpl_serialVersionUID
#define BeaconListenerImpl_serialVersionUID 0LL
#ifdef __cplusplus
}
#endif
#endif
